version: "3.9"
services:
  sqlserver:
    container_name: sql_server
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Password1
      ACCEPT_EULA: "Y"
    ports:
      - "5100:1433"

  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"