name: Release

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate package
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          dotnet pack -c Release -o out -p:PackageVersion=$TAG_NAME
      - name: Push nuget
        run: |
          dotnet nuget push out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SERVER }}